"use client"

import { useRef } from "react"
import { motion, useInView } from "framer-motion"
import { Sparkles, Code2, Palette, Server, Cpu, Wand2 } from "lucide-react"

const technologies = [
  {
    name: "Google Gemini",
    description: "Rule interpretation, multimodal reasoning, and strategy generation",
    icon: Sparkles,
    color: "#00d4ff",
  },
  {
    name: "Google AI Studio",
    description: "Prompt design and AI-driven code generation",
    icon: Wand2,
    color: "#ff6b9d",
  },
  {
    name: "React",
    description: "Modern frontend framework for building interactive UIs",
    icon: Code2,
    color: "#61dafb",
  },
  {
    name: "Tailwind CSS",
    description: "Utility-first CSS framework for rapid styling",
    icon: Palette,
    color: "#38bdf8",
  },
  {
    name: "TypeScript",
    description: "Type-safe JavaScript for reliable code",
    icon: Code2,
    color: "#3178c6",
  },
  {
    name: "Node.js",
    description: "Backend runtime for server-side logic",
    icon: Server,
    color: "#68a063",
  },
]

export function TechSection() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: "-100px" })

  return (
    <section id="technology" ref={ref} className="relative py-24 md:py-32 overflow-hidden">
      <div className="absolute inset-0 bg-linear-to-b from-background via-secondary/10 to-background" />

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="inline-block px-4 py-1.5 rounded-full bg-primary/20 text-primary text-sm font-medium mb-4">
            🛠️ Technology
          </span>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4 text-balance">
            Built with <span className="text-primary">Modern Tech</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Powered by cutting-edge AI and development technologies
          </p>
        </motion.div>

        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 md:gap-6">
          {technologies.map((tech, index) => (
            <motion.div
              key={tech.name}
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group"
            >
              <div className="relative h-full p-6 rounded-2xl bg-card border border-border text-center hover:border-primary/50 transition-all duration-300">
                <div
                  className="w-14 h-14 mx-auto rounded-xl flex items-center justify-center mb-4 transition-transform group-hover:scale-110"
                  style={{ backgroundColor: `${tech.color}20` }}
                >
                  <tech.icon className="w-7 h-7" style={{ color: tech.color }} />
                </div>
                <h3 className="font-semibold text-foreground mb-2 text-sm">{tech.name}</h3>
                <p className="text-muted-foreground text-xs leading-relaxed hidden md:block">{tech.description}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* AI Generated Code Note */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.6 }}
          className="mt-16 p-6 md:p-8 rounded-2xl bg-card border border-primary/30 max-w-3xl mx-auto"
        >
          <div className="flex items-start gap-4">
            <div className="shrink-0 w-12 h-12 rounded-xl bg-primary/20 flex items-center justify-center">
              <Cpu className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h3 className="font-semibold text-lg text-foreground mb-2">🤖 AI-Generated Code</h3>
              <p className="text-muted-foreground leading-relaxed">
                A defining aspect of game.AI is its AI-assisted development. Frontend and backend code were largely
                generated by Google Gemini, with developers refining and iterating using prompt-based guidance. This
                enabled rapid prototyping and AI-first experimentation.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
